name: Build/Test

on:
  workflow_call:
    secrets:
      CHARMHUB_TOKEN:
        required: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
      - name: Install dependencies
        run: python3 -m pip install tox
      - name: Run linters
        run: tox -e lint

  unit-test:
    name: Unit tests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
      - name: Install dependencies
        run: python -m pip install tox
      - name: Run tests
        run: tox -e unit

  integration-test:
    name: Integration tests (microk8s)
    runs-on: ubuntu-22.04
    needs:
      - lint
      - unit-test
    steps:
      - name: Checkout local
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          path: repo
      - name: run killsnoop
        uses: JarvusInnovations/background-action@v1
        with:
          run: |
            sudo apt-get update && sudo apt-get -y install bpfcc-tools python3-psutil && ls && find . && sudo python3 repo/src/killsnoop.py &
          wait-on: |
            file:///tmp/compiled
          tail: true
          log-output-resume: stderr
          wait-for: 10m
          log-output: stderr,stdout # same as true
          log-output-if: true
          working-directory: /tmp

      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          provider: microk8s
          channel: 1.26-strict/stable
          juju-channel: 3.1/stable
          microk8s-group: snap_microk8s
      - name: Run integration tests
        run: tox -e integration
